const unsplash = (id, host = "images") =>
  `https://${host}.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=70`;

const hosts = [
  { key: "ananya", name: "Ananya Rao", email: "ananya@example.com" },
  { key: "vikram", name: "Vikram Thakur", email: "vikram@example.com" },
  { key: "meera", name: "Meera Nair", email: "meera@example.com" },
  { key: "farhan", name: "Farhan Qureshi", email: "farhan@example.com" },
  { key: "arjun", name: "Arjun Mehta", email: "arjun@example.com" },
];

const guests = [
  { key: "priya", name: "Priya Sharma", email: "priya@example.com" },
  { key: "rohan", name: "Rohan Kapoor", email: "rohan@example.com" },
  { key: "sneha", name: "Sneha Iyer", email: "sneha@example.com" },
  { key: "karan", name: "Karan Malhotra", email: "karan@example.com" },
  { key: "aditya", name: "Aditya Verma", email: "aditya@example.com" },
];

const listings = [
  {
    host: "meera",
    title: "Backwater houseboat with a private deck",
    description:
      "A traditional kettuvallam converted into a two-bedroom houseboat, moored on a quiet canal away from the main tourist stretch.\n\nMornings start with filter coffee on the upper deck; the crew cooks Kerala meals on board with fish from the local market. Air conditioning in the bedrooms runs from 9 pm to 6 am. We can arrange a short cruise through the paddy canals on request.",
    propertyType: "houseboat",
    location: "Alappuzha, Kerala",
    country: "India",
    coordinates: [76.3388, 9.4981],
    pricePerNight: 9500,
    cleaningFee: 0,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["ac", "breakfast", "tv"],
    images: [
      unsplash("photo-1552733407-5d5c46c3bb3b"),
      unsplash("photo-1501785888041-af3ef285b470"),
    ],
  },
  {
    host: "ananya",
    title: "Boutique pool villa near Anjuna Beach",
    description:
      "A three-bedroom villa with a 10 m pool, ten minutes by scooter from Anjuna and Vagator. The ground floor opens onto the pool deck; bedrooms upstairs each have their own bathroom.\n\nThe kitchen is fully equipped and a housekeeper visits daily. Quiet hours after 10 pm as the villa is in a residential lane.",
    propertyType: "villa",
    location: "Anjuna, Goa",
    country: "India",
    coordinates: [73.74, 15.5736],
    pricePerNight: 14000,
    cleaningFee: 1500,
    maxGuests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3,
    amenities: ["wifi", "ac", "pool", "kitchen", "parking", "tv", "washer"],
    images: [
      unsplash("photo-1571896349842-33c89424de2d"),
      unsplash("photo-1622396481328-9b1b78cdd9fd"),
      unsplash("photo-1488462237308-ecaa28b729d7"),
    ],
  },
  {
    host: "ananya",
    title: "Coffee estate bungalow with pool",
    description:
      "A restored planter's bungalow in the middle of a working 40-acre coffee and pepper estate. Four large bedrooms, a pool overlooking the valley, and walking trails through the plantation.\n\nBreakfast is home-style Kodava food; dinner can be arranged on request. The last 2 km is an estate road, so a car with decent ground clearance helps in the monsoon.",
    propertyType: "house",
    location: "Madikeri, Coorg",
    country: "India",
    coordinates: [75.7382, 12.4244],
    pricePerNight: 11000,
    cleaningFee: 1000,
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 4,
    amenities: ["wifi", "pool", "breakfast", "parking", "kitchen", "fireplace"],
    images: [
      unsplash("photo-1566073771259-6a8506099945"),
      unsplash("photo-1578645510447-e20b4311e3ce"),
    ],
  },
  {
    host: "meera",
    title: "Tropical garden villa by the cliffs",
    description:
      "Two thatched cottages around a shared plunge pool, set in a garden of coconut palms and heliconias. The North Cliff walkway and beach are a seven-minute walk away.\n\nEach cottage has an outdoor shower and a verandah. We serve breakfast by the pool and are happy to book Ayurvedic treatments nearby.",
    propertyType: "villa",
    location: "Varkala, Kerala",
    country: "India",
    coordinates: [76.7163, 8.7379],
    pricePerNight: 8200,
    cleaningFee: 500,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["wifi", "ac", "pool", "breakfast"],
    images: [
      unsplash("photo-1520250497591-112f2f40a3f4"),
      unsplash("photo-1622396481328-9b1b78cdd9fd"),
    ],
  },
  {
    host: "ananya",
    title: "Sea-facing suite with infinity pool",
    description:
      "A one-bedroom suite on the east coast of Swaraj Dweep with an infinity pool that looks straight onto the sea. Ideal for couples.\n\nThe ferry from Port Blair takes about 90 minutes; we can arrange a pickup from the jetty. Scuba centres and Kalapathar beach are nearby. Power backup covers the whole property.",
    propertyType: "villa",
    location: "Swaraj Dweep (Havelock), Andaman and Nicobar Islands",
    country: "India",
    coordinates: [92.9876, 11.9761],
    pricePerNight: 16500,
    cleaningFee: 0,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["wifi", "ac", "pool", "breakfast"],
    images: [
      unsplash("photo-1571003123894-1f0594d2b5d9"),
      unsplash("photo-1502784444187-359ac186c5bb"),
      unsplash("photo-1488462237308-ecaa28b729d7"),
    ],
  },
  {
    host: "vikram",
    title: "Hillside cottage with Solang Valley views",
    description:
      "A two-bedroom stone-and-wood cottage above Old Manali, with wide views of the valley and the Pir Panjal range. There is a wood-burning fireplace in the living room and room heaters in both bedrooms.\n\nThe cottage is a 10-minute uphill walk from where cars can stop; we help with luggage. Good base for Solang, Sethan and Hampta Pass treks.",
    propertyType: "cottage",
    location: "Manali, Himachal Pradesh",
    country: "India",
    coordinates: [77.1892, 32.2432],
    pricePerNight: 4800,
    cleaningFee: 500,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["wifi", "heating", "kitchen", "fireplace", "workspace"],
    images: [
      unsplash("photo-1464822759023-fed622ff2c3b"),
      unsplash("photo-1493246507139-91e8fad9978e"),
      unsplash("photo-1501785888041-af3ef285b470"),
    ],
  },
  {
    host: "vikram",
    title: "Riverside glamping tent above the Ganga",
    description:
      "A spacious canvas tent on a raised wooden platform, with a proper bed, attached bathroom and a sit-out facing the river. The camp is 16 km upstream of Rishikesh, away from the traffic.\n\nBreakfast and dinner are served in the common dining tent. Rafting and short forest hikes can be arranged at the reception.",
    propertyType: "glamping",
    location: "Shivpuri, Rishikesh",
    country: "India",
    coordinates: [78.3876, 30.1378],
    pricePerNight: 3200,
    cleaningFee: 0,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["breakfast", "parking"],
    images: [
      unsplash("photo-1504280390367-361c6d9f38f4"),
      unsplash("photo-1578645510447-e20b4311e3ce"),
    ],
  },
  {
    host: "vikram",
    title: "Pinewood family home in Kasauli",
    description:
      "A three-bedroom family home set among pine trees, a short drive from the Mall Road. Big windows, a sunny lawn and a covered porch for rainy evenings.\n\nThe kitchen is fully stocked and there is a caretaker on site who can cook simple meals. Wi-Fi is fibre, reliable enough for video calls.",
    propertyType: "house",
    location: "Kasauli, Himachal Pradesh",
    country: "India",
    coordinates: [76.965, 30.8983],
    pricePerNight: 7500,
    cleaningFee: 800,
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ["wifi", "heating", "kitchen", "parking", "fireplace", "tv", "workspace", "pets"],
    images: [
      unsplash("photo-1618140052121-39fc6db33972"),
      unsplash("photo-1493246507139-91e8fad9978e"),
    ],
  },
  {
    host: "ananya",
    title: "Beach hut steps from Palolem",
    description:
      "A simple, well-kept wooden hut right behind the dunes at the quieter southern end of Palolem. You hear the sea all night.\n\nThe hut has a fan, mosquito net and an attached bathroom with hot water. Breakfast is served at our beach café. Open from October to May.",
    propertyType: "cottage",
    location: "Palolem, Goa",
    country: "India",
    coordinates: [74.0232, 15.01],
    pricePerNight: 3500,
    cleaningFee: 0,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["wifi", "breakfast"],
    images: [
      unsplash("photo-1602088113235-229c19758e9f"),
      unsplash("photo-1488462237308-ecaa28b729d7"),
      unsplash("photo-1622396481328-9b1b78cdd9fd"),
    ],
  },
  {
    host: "vikram",
    title: "Lakeside camp in the Kumaon hills",
    description:
      "Tents on the edge of a forested lake, about 20 minutes from Bhimtal town. Each tent has twin beds, warm bedding and a shared bathroom block with hot water.\n\nEvenings are around the bonfire; meals are simple Kumaoni food. Kayaks are available for guests to use on the lake.",
    propertyType: "glamping",
    location: "Bhimtal, Uttarakhand",
    country: "India",
    coordinates: [79.5596, 29.3446],
    pricePerNight: 2900,
    cleaningFee: 0,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: ["breakfast", "parking", "pets"],
    images: [
      unsplash("photo-1602391833977-358a52198938"),
      unsplash("photo-1501785888041-af3ef285b470"),
    ],
  },
  {
    host: "meera",
    title: "Forest dome above the tea gardens",
    description:
      "A geodesic dome on stilts at the edge of a private forest, with a skylight over the bed for stargazing. Reached by a short wooden staircase.\n\nThe dome has an attached bathroom and a small deck. Breakfast is brought up each morning. Great for birdwatching; not suitable for small children because of the stairs.",
    propertyType: "cabin",
    location: "Wayanad, Kerala",
    country: "India",
    coordinates: [76.132, 11.6854],
    pricePerNight: 6200,
    cleaningFee: 0,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["wifi", "breakfast", "parking"],
    images: [
      unsplash("photo-1521401830884-6c03c1c87ebb"),
      unsplash("photo-1578645510447-e20b4311e3ce"),
    ],
  },
  {
    host: "farhan",
    title: "Snow-view chalet near the Gondola",
    description:
      "A timber-and-stone chalet five minutes from the Gulmarg Gondola base station. Three bedrooms, a bukhari-heated living room and a drying room for ski gear.\n\nKashmiri breakfast is included and dinner is available on request. In peak winter the road can close after heavy snow; we keep guests updated.",
    propertyType: "cabin",
    location: "Gulmarg, Jammu and Kashmir",
    country: "India",
    coordinates: [74.3805, 34.0484],
    pricePerNight: 9000,
    cleaningFee: 1000,
    maxGuests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    amenities: ["wifi", "heating", "fireplace", "breakfast", "parking"],
    images: [
      unsplash("premium_photo-1670963964797-942df1804579", "plus"),
      unsplash("photo-1493246507139-91e8fad9978e"),
    ],
  },
  {
    host: "farhan",
    title: "Riverside log cabin on the Lidder",
    description:
      "A two-bedroom log cabin beside the Lidder river, among pine and deodar trees. The sound of the river is constant, so light sleepers may want earplugs.\n\nBetaab Valley and Aru are a short drive away. The kitchen has everything for self-catering, and a local cook can be arranged.",
    propertyType: "cabin",
    location: "Pahalgam, Jammu and Kashmir",
    country: "India",
    coordinates: [75.315, 34.0161],
    pricePerNight: 6800,
    cleaningFee: 700,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["heating", "fireplace", "kitchen", "parking"],
    images: [
      unsplash("photo-1470165301023-58dab8118cc9"),
      unsplash("photo-1501785888041-af3ef285b470"),
    ],
  },
  {
    host: "farhan",
    title: "Heritage houseboat on Dal Lake",
    description:
      "A walnut-wood houseboat built in the 1940s, with carved ceilings and two bedrooms. Moored on the quieter side of Dal Lake, connected to the shore by shikara.\n\nBreakfast and dinner are served on board. Early morning floating-market trips can be arranged with our shikara wala.",
    propertyType: "houseboat",
    location: "Srinagar, Jammu and Kashmir",
    country: "India",
    coordinates: [74.8683, 34.1106],
    pricePerNight: 7200,
    cleaningFee: 0,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["wifi", "heating", "breakfast", "tv"],
    images: [
      unsplash("photo-1476514525535-07fb3b4ae5f1"),
      unsplash("photo-1501785888041-af3ef285b470"),
    ],
  },
  {
    host: "ananya",
    title: "Plantation homestay in the Baba Budangiri hills",
    description:
      "Two guest rooms in our family home on a coffee estate. Meals are shared with the family and made from estate produce.\n\nWe offer a free guided walk through the plantation and a coffee-processing demo in season (December–February). Mullayanagiri peak is a 40-minute drive.",
    propertyType: "farmstay",
    location: "Chikkamagaluru, Karnataka",
    country: "India",
    coordinates: [75.772, 13.3161],
    pricePerNight: 4200,
    cleaningFee: 0,
    maxGuests: 5,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    amenities: ["wifi", "breakfast", "parking", "pets"],
    images: [
      unsplash("photo-1586375300773-8384e3e4916f"),
      unsplash("photo-1578645510447-e20b4311e3ce"),
    ],
  },
  {
    host: "arjun",
    title: "Modern private-pool villa in Lonavala",
    description:
      "A four-bedroom villa with a private pool and a large lawn, 90 minutes from Mumbai and 60 from Pune. Designed for families and groups of friends.\n\nThere is a caretaker on site, a fully equipped kitchen and an outdoor barbecue. Loud music is not allowed after 10 pm per society rules.",
    propertyType: "villa",
    location: "Lonavala, Maharashtra",
    country: "India",
    coordinates: [73.4062, 18.7546],
    pricePerNight: 18500,
    cleaningFee: 2500,
    maxGuests: 10,
    bedrooms: 4,
    beds: 6,
    bathrooms: 4,
    amenities: ["wifi", "ac", "pool", "kitchen", "parking", "tv", "workspace", "washer"],
    images: [
      unsplash("photo-1602343168117-bb8ffe3e2e9f"),
      unsplash("photo-1578645510447-e20b4311e3ce"),
    ],
  },
  {
    host: "vikram",
    title: "Timber cabin in Tirthan Valley",
    description:
      "A one-room timber cabin with a loft, on an apple orchard above the Tirthan river. Close to the Great Himalayan National Park entry at Gushaini.\n\nHome-cooked Himachali meals are available. Mobile signal is patchy; the Wi-Fi works but is slow. Dogs welcome.",
    propertyType: "cabin",
    location: "Tirthan Valley, Himachal Pradesh",
    country: "India",
    coordinates: [77.36, 31.63],
    pricePerNight: 3900,
    cleaningFee: 300,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: ["heating", "breakfast", "pets", "parking"],
    images: [
      unsplash("photo-1587381420270-3e1a5b9e6904"),
      unsplash("photo-1493246507139-91e8fad9978e"),
    ],
  },
  {
    host: "meera",
    title: "Lakeview cottage in Kodaikanal",
    description:
      "A colonial-era cottage a short walk from Kodaikanal Lake. Two bedrooms, a sitting room with a fireplace, and a garden full of hydrangeas.\n\nNights are cold year-round, so we provide heaters and extra blankets. Coaker's Walk and Bryant Park are within walking distance.",
    propertyType: "cottage",
    location: "Kodaikanal, Tamil Nadu",
    country: "India",
    coordinates: [77.4892, 10.2381],
    pricePerNight: 5200,
    cleaningFee: 500,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["wifi", "heating", "kitchen", "fireplace"],
    images: [
      unsplash("photo-1439066615861-d1af74d74000"),
      unsplash("photo-1501785888041-af3ef285b470"),
    ],
  },
  {
    host: "ananya",
    title: "Beachfront bungalow on Shaheed Dweep",
    description:
      "A thatched bungalow directly on the sand at Laxmanpur beach, known for its sunsets. Snorkelling at the natural bridge is a short cycle ride away.\n\nThe bungalow has air conditioning, an outdoor shower and a hammock. Breakfast is included; the island has a few good seafood restaurants.",
    propertyType: "cottage",
    location: "Shaheed Dweep (Neil Island), Andaman and Nicobar Islands",
    country: "India",
    coordinates: [93.029, 11.832],
    pricePerNight: 10500,
    cleaningFee: 0,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["wifi", "ac", "breakfast"],
    images: [
      unsplash("photo-1499793983690-e29da59ef1c2"),
      unsplash("photo-1502784444187-359ac186c5bb"),
      unsplash("photo-1488462237308-ecaa28b729d7"),
    ],
  },
  {
    host: "arjun",
    title: "Lagoon-side cottage on Agatti",
    description:
      "A two-bedroom cottage facing the Agatti lagoon, with shallow turquoise water a few steps from the verandah.\n\nVisiting Lakshadweep requires an entry permit; we share the process after booking and help with the paperwork. Meals are included because there are few restaurants on the island.",
    propertyType: "cottage",
    location: "Agatti Island, Lakshadweep",
    country: "India",
    coordinates: [72.192, 10.859],
    pricePerNight: 12000,
    cleaningFee: 0,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["ac", "breakfast", "wifi"],
    images: [
      unsplash("photo-1585543805890-6051f7829f98"),
      unsplash("photo-1502784444187-359ac186c5bb"),
      unsplash("photo-1622396481328-9b1b78cdd9fd"),
    ],
  },
];

const reviewComments = [
  [5, "Exactly as described and spotlessly clean. Check-in was easy and the host replied within minutes whenever we had a question."],
  [5, "One of the most peaceful places we've stayed. The breakfast alone was worth it. Would happily come back."],
  [4, "Lovely setting and a comfortable bed. The approach road is a bit rough, so plan for that, but the stay itself was great."],
  [5, "The photos don't do the view justice. Thoughtful touches everywhere, from the fresh towels to the local snacks."],
  [4, "Great location and a very helpful host. Water pressure in the shower was low, otherwise no complaints."],
  [5, "We came for a long weekend and wished we had booked a week. Quiet, well-kept, and the host's recommendations were spot on."],
  [3, "Nice place overall, but it was noisier than expected on the weekend. The host was apologetic and helpful."],
  [4, "Good value for the price. Clean rooms, friendly staff and easy to reach. Wi-Fi was a little slow in the evenings."],
  [5, "Perfect for a family trip. The kids loved it, and the kitchen had everything we needed to cook our own meals."],
  [4, "Beautiful property and very comfortable. Would have liked a few more cooking basics, but the host sorted it quickly."],
];

module.exports = { hosts, guests, listings, reviewComments };
